#!/usr/bin/env ruby
require 'test/unit'

class TestManual < Test::Unit::TestCase
  def test_manual
    system('ruby examples/usage')
    print 'Is the "Please match usage." message above red?(Y/n): '
    flunk unless $stdin.gets.strip == 'Y'
  end
end
