#!/usr/bin/env ruby
require "json"
require_relative "../lib/help_parser"

HELP = <<-HELP
### The Help ###
Usage:
  #{File.basename($0)} [:options+]
Options:
  -a
  -b
  -c
  -d
  -e
Conditional:
  a b
  c d e
# Breaks out!
  cacahuates
HELP

VERSION = "1.0.0"

OPTIONS = HelpParser[VERSION, HELP]
puts OPTIONS._hash.to_json
