#!/usr/bin/env ruby
require_relative '../lib/help_parser'

HELP = <<~HELP
  Usage:
    cmd :options+ <pet> <more>+
    cmd ints <many>+
    cmd floats <much>+
  Options:
    --age
    --weight
HELP

HelpParser.float(:weight)
HelpParser.integer(:age)
HelpParser.float(:much)
HelpParser.integer(:many)

OPTIONS = HelpParser[nil, HELP, ['cmd']+ARGV]

if OPTIONS.pet?
  print "Pet: #{OPTIONS.pet} Age: #{OPTIONS.age} Weight: #{OPTIONS.weight}"
  puts " More: #{OPTIONS.more.join(',')}"
elsif OPTIONS.many?
  puts "Many Total: #{OPTIONS.many.sum}"
elsif OPTIONS.much?
  puts "Much Total: #{OPTIONS.much.sum}"
else
  puts OPTIONS.to_h
end
