#!/usr/bin/env ruby
require_relative "../lib/help_parser"

# README help synopsis from version VI, Tweeker.
HELP = <<-HELP
# The Tweeker Command #
Usage:
  tweeker [:options+] <args>+
  tweeker :alternate+ <arg=NAME>
Options:
  -v --version       \t Give version and quit
  -h --help          \t Give help and quit
  -s --long          \t Short long synonyms
  --name=NAME        \t Typed
  --number 5         \t Defaulted
  --value=FLOAT 1.23 \t Typed and Defaulted
  -a --all=YN y      \t Short, long, typed, and defaulted
Alternate:
  -V                 \t Just short
  --to_be
  --not_to_be
Types:
  NAME  /^[A-Z][a-z]+$/
  FLOAT /^\\d+\\.\\d+$/
  YN    /^[YNyn]$/
Exclusive:
  to_be not_to_be    \t Tells parser these are mutually exclusive keys
# Notes #
Blah blah blah
HELP

VERSION = "6.5.0"

# Macros:
HelpParser.string(:name)  # for options.name   : String
HelpParser.strings(:args) # for options.args   : Array(String)
HelpParser.float(:value)  # for options.value  : Float
HelpParser.int?(:number)  # for options.number : Int32 | Nil

HelpParser.run(VERSION, HELP, ["tweeker"]+ARGV) do |options|
  hash = options._hash
  pp hash # to inspect the hash

  pp options.name  if hash["name"]
  pp options.args  if hash["args"]
  pp options.value if hash["value"]
  pp options.number?
end
